"""Exact tools for digit discrepancies in Pell convergents."""

from .core import (
    VerificationResult,
    actual_digit_event,
    base_digits,
    boundary_correction,
    decimal_theoretical_return_gap,
    digit_event_indices,
    floor_log_base,
    ideal_rotation_event,
    is_positive_base_power,
    pell_pair,
    pell_pairs,
    predicted_digit_event,
    sign_a_plus_b_sqrt2,
    verify_rectangle,
)
from .period_one import (
    PeriodOneTerm,
    PeriodOneVerificationResult,
    period_one_convergents,
    period_one_corrections_below_one,
    period_one_ideal_discrepancy,
    period_one_predicted_discrepancy,
    period_one_terms,
    period_one_xi_at_least_base,
    sign_a_plus_b_sqrt_d,
    verify_period_one_grid,
)

__all__ = [
    "VerificationResult",
    "actual_digit_event",
    "base_digits",
    "boundary_correction",
    "decimal_theoretical_return_gap",
    "digit_event_indices",
    "floor_log_base",
    "ideal_rotation_event",
    "is_positive_base_power",
    "pell_pair",
    "pell_pairs",
    "predicted_digit_event",
    "sign_a_plus_b_sqrt2",
    "verify_rectangle",
    "PeriodOneTerm",
    "PeriodOneVerificationResult",
    "period_one_convergents",
    "period_one_corrections_below_one",
    "period_one_ideal_discrepancy",
    "period_one_predicted_discrepancy",
    "period_one_terms",
    "period_one_xi_at_least_base",
    "sign_a_plus_b_sqrt_d",
    "verify_period_one_grid",
]
